[theme]
base = "dark"
primaryColor = "#D99A45"
backgroundColor = "#101A14"
secondaryBackgroundColor = "#172219"
textColor = "#EEE3C7"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = true
